---
Name: multidomain
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\RequestProcessor:
    properties:
      filters:
        - '%$MultiDomainRequestFilter'
  MultiDomainRequestFilter:
    class: SilverStripe\MultiDomain\MultiDomainRequestFilter;

SilverStripe\MultiDomain\MultiDomain:
  allow_subdomains: false
