---
Name: multidomain
---

SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        MultiDomainMiddleware: %$MultiDomainMiddleware
  MultiDomainMiddleware:
    class: 'SilverStripe\MultiDomain\MultiDomainMiddleware'

SilverStripe\MultiDomain\MultiDomain:
  allow_subdomains: false
